### ISSUE TITLE
Share VS Code setup guide 

### ISSUE THREAD

**Issue by kohheepeace** [nebulab/erb-formatter-vscode#1]
First of all, thank you very much for creating this awesome plugin. This is very very helpful for me cause `prettier-plugin-erb` is not working well.

I had a bit of trouble getting this plugin to work in my environment, please allow me to share the setup guide in this issue.

**`.vsocde/settings.json`**
```json
{
  "editor.formatOnSave": true,
...
  "[ruby]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[erb]": {
    "editor.defaultFormatter": "elia.erb-formatter" // 👈 I need to add this line.
  },
...
}
```

Also please don't forget to add `gem 'erb-formatter'` in your Gemfile.

Thanks.

**Comment by kohheepeace** [comment]
Close due to this is not issue but for just sharing tips.

**Comment by overdrivemachines** [comment]
Thank you for sharing. I wish the author added this to the README.md
